# Generated by Django 4.0.6 on 2022-07-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_song_related_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='related_model',
            new_name='related_object',
        ),
    ]
